config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'pages/home'
  root 'public_recipes#index'
  get 'general_shopping_list/index'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
   resources :recipes, only: [:index, :show, :new, :create] do
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :foods, only: [:index, :show, :new, :create, :destroy]
  resources :shopping_list, only: [:index, :create]
  resources :inventories do
    resources :inventory_foods, only: [:new, :create, :destroy, :index]
  end

end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :inventory, foreign_key: :inventory_id
  belongs_to :food, foreign_key: :food_id

  validates :quantity, presence: true, length: { maximum: 50 }
end

app/controllers/inventory_food_controller.rb
class InventoryFoodController < ApplicationController
  def index
    @inventory_food = InventoryFood.all
  end

  def show
    @inventory_food = InventoryFood.find(params[:id])
  end

  def new
    @inventory_food = InventoryFood.new
    @inventory = Inventory.find(params[:inventory_id])
  end

  def create
    @inventory_food = InventoryFood.create(inventory_food_params)
    @inventory_food.inventory_id = params[:inventory_id]
    @inventory_food.food_id = params[:food_id]
    @inventory_food.save
    redirect_to user_inventory_path(current_user.id, params[:inventory_id]),
                notice: 'Inventory Food was successfully created.'
  end

  def destroy
    @inventory_food = InventoryFood.find_by(id: params[:id])

    redirect_to user_inventory_path(current_user.id, params[:inventory_id]),
                notice: 'Inventory Food was successfully deleted.'

    if @inventory_food.destroy
      flash[:success] = 'Inventory deleted'
    else
      flash.now[:error] = 'Inventory Not Deleted'
    end
  end

  private

  def inventory_food_params
    params.require(:@inventory_food).permit(:quantity, :food_id, :inventory_id)
  end
end

app/controllers/inventory_foods_controller.rb
class InventoryFoodsController < ApplicationController
  def index
    @inventory_food = InventoryFood.all
  end

  def show
    @inventory_food = InventoryFood.find(params[:id])
  end

  def new
    @inventory_food = InventoryFood.new
    @inventory = Inventory.find(params[:inventory_id])

    respond_to do |format|
      format.html { render :new, locals: { inventory_food: @inventory_food } }
    end
  end

  def create
    @inventory_food = InventoryFood.create(inventory_food_params)
    @inventory_food.inventory_id = params[:inventory_id]
    @inventory_food.food_id = params[:food_id]
    @inventory_food.save
    redirect_to inventory_path(params[:inventory_id]),
                notice: 'Inventory Food was successfully created.'
  end

  def destroy
    @inventory_food = InventoryFood.find_by(id: params[:id])

    redirect_to inventory_path(params[:inventory_id]),
                notice: 'Inventory Food was successfully deleted.'

    if @inventory_food.destroy
      flash[:success] = 'Inventory deleted'
    else
      flash.now[:error] = 'Inventory Not Deleted'
    end
  end

  private

  def inventory_food_params
    params.require(:@inventory_food).permit(:quantity, :food_id, :inventory_id)
  end
end

app/helpers/inventory_food_helper.rb
module InventoryFoodHelper
end

app/views/inventory_foods/index.html.erb
<div class="food-view">
<div class="d-flex justify-content-end me-5 p-2">
<%= link_to 'Add Food', new_inventory_inventory_food_path( @inventory.id), class: "btn btn-dark p-3" %>
</div>
<hr>
<table class=" table table-striped table-bordered table-hover text-center" style="width: 80%; margin-top: 3re; margin-inline:auto">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% InventoryFood.all.each do |infood| %>
        <tr>
            <th scope="row"><%= infood.id %></th>
            <td><%= infood.food.name %></td>
            <td><%= infood.quantity %></td>
            <td>
            
            <%= button_to "Delete", inventory_inventory_food_path(@inventory, infood), data: {turbo: false}, method: :delete, class: "btn bg-red-300" %>
            
            </td>
        </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/inventory_foods/new.html.erb
<div class="flex justify-center mt-48 mb-48 container mx-auto">
  <div class="w-3/5 bg-white shadow-lg pb-10 px-10 pt-5">
    <h1 class="create-title text-center">Add A New Inventory Food</h1>
        <%= form_with model:@inventory_food, url: inventory_inventory_foods_path(inventory_id: params[:inventory_id]), method: :post, local: true, scope: :@inventory_food do |f| %>
            <div class="form-group">
                <div class="form-outline mb-4">
                    <%= f.label :quantity, class: "form-label" %><br />
                    <%= f.text_field :quantity, class: 'py-2 px-4 mt-3 border w-full focus:outline-orange-400' %>
                </div>
                <div class="form-outline mb-4">
                    <%= f.label :inventory_id, class: "form-label" %><br />
                    <%= f.collection_select(:inventory_id, Inventory.all, :id, :name, class: "form-control form-control-lg" ) %>
                </div>
                <div class="form-outline mb-4">
                    <%= f.label :food_id, class: "form-label" %><br />
                    <%= f.select(:food_id, Food.all.map{|u| [u.name, u.id]}, class: "form-control form-control-lg" ) %>
                </div>

                <div class="submit-btn">
                    <%= f.submit 'Save' ,class: "btn bg-teal-400"  %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/inventory_foods/show.html.erb
<h1>InventoryFood#show</h1>
<p>Find me in app/views/inventory_food/show.html.erb</p>