config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'pages/home'
  root 'public_recipes#index'
  get 'general_shopping_list/index'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
   resources :recipes, only: [:index, :show, :new, :create] do
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :foods, only: [:index, :show, :new, :create, :destroy]
  resources :shopping_list, only: [:index, :create]
  resources :inventories do
    resources :inventory_foods, only: [:new, :create, :destroy, :index]
  end

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates :preparation_time, presence: true, comparison: { greater_than: 0 }
  validates :cooking_time, presence: true, comparison: { greater_than: 0 }
  validates :description, presence: true, length: { minimum: 3, maximum: 300 }
  validates :public, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @current_user = current_user
    @recipes = @current_user.recipes
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @user = current_user
    @recipe = @user.recipes.find(params[:id])
    @foods = RecipeFood.where(recipe_id: @recipe.id)
    @recipe_foods = @recipe.recipe_foods
    @inventories = Inventory.where(user: current_user)

    @inventory_data = Inventory.all
    return if params[:inventory_id].nil?

    # rubocop:disable Layout/LineLength
    @foods = RecipeFood.joins(:food).select('foods.id as food_id, name as food_name, quantity, price, quantity * price as value, recipe_id').where(recipe_id: params[:id])
    # rubocop:enable Layout/LineLength
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_url, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        flash[:error] = 'Error: recipe could not be saved'
        redirect_to new_recipe_url
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    render :edit, status: :unprocessable_entity unless @recipe.update(public: !@recipe.public)
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time, :public)
  end
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div>
      <h2><%= pluralize(recipe.errors.count, "error") %> this recipe can not be saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="flex justify-center mt-40 mb-30 container mx-auto">
  <div class="w-3/5 bg-white shadow-lg pb-10 px-10 pt-5">
    <%=form.text_field :name, class: 'py-2 px-4 border w-full focus:outline-orange-400', placeholder: 'Recipe name' %><br />
    <%=form.text_area :description, class: 'py-2 px-4 border w-full focus:outline-orange-400', placeholder: 'Recipe description' %><br />
    <%=form.number_field :preparation_time, class: 'py-2 px-4 border w-full focus:outline-cyan-400', placeholder:'Prepration time',value: "%H:%M",min: 'hh:mm:ss',max: 'hh:mm:ss'%><br />
    <%=form.number_field :cooking_time, class: 'py-2 px-4 border w-full focus:outline-orange-400', placeholder:'Cooking time',value: "%H:%M",min: 'hh:mm:ss',max: 'hh:mm:ss'%><br />
    <h3>Public</h3>
    <div>
    <%= form.radio_button :public, "true" %>
    <%= form.label :public, "true" %>

    <%= form.radio_button :public, "false" %>
    <%= form.label :public, "false" %>
    </div>
    <%= form.submit 'Create', class: 'bg-orange-500 py-3 px-6 text-white cursor-pointer hover:bg-orange-700'%>
  </div>
  </div>
<% end %>

app/views/recipes/_recipe.htm.erb
<div id="<%= dom_id recipe %>">
	<p><%=recipe.name%></p>
	<p><%=recipe.description%></p>
	<%= button_to "Remove", recipe_path(id:recipe.id), method: :delete%>	
</div>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" class=" recipe-details flex justify-between w-4/5 mb-4">
	<div class="flex ">
		 <h2 class="mb-4">  <%= link_to recipe.name, recipe_path(recipe.id) %> </h2>
		
		<%= button_to "Remove", recipe_path(id:recipe.id), method: :delete, class:'w-fit btn bg-red-300'%>


	</div>
	<p class="ml-10"><%=recipe.description%></p>
</div>

app/views/recipes/_recipe_details.html.erb
<div class="flex flex-col items-center justify-center">

	<h1 class="text-3xl text-gray-700 font-semibold text-center"><%=recipe.name%></h1>
	<p class="font-semibold text-gray-600 text-center">Preparation time: <%=recipe.preparation_time%></p>
	<div class="flex justify-end">
		 <%=form_with url: recipe_path, method: :put do %>
             public: <label class="switch">
               <%= check_box_tag "",@recipe.public,@recipe.public, onchange: "this.form.submit()" %>
               <span class="slider round"></span>
             </label>
             <%end%> 
  </div>
  <p class="font-semibold text-gray-600 text-center">Cooking time: <%=recipe.cooking_time%></p>
  <p class="text-center font-semibold text-xl">Description: <%=recipe.description%></p>

  <%= link_to "Back to recipes", recipes_path, class:"no-underline hover:underline text-purple-700 text-lg"%>

  <div class="d-flex justify-content-between">
    <button type="button" class="bg-teal-500 btn open-btn">Generate Shopping List</button>
    <%= link_to "Add Ingredients", new_recipe_recipe_food_path(@recipe), class:"btn"%>
  </div>
  <table class="table table-striped table-dark ">
    <thead>
      <tr class="divide-x">
        <th class="flex align-left pl-1">Food</th>
        <th class="ml-0">Quantity</th>
        <th class="flex pl-1">Value</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @recipe_foods.each do |recipe_food| %>
        <tr
          class="odd:bg-gray-200 divide-x divide-gray-300"
        >
          <td class="flex align-top m-auto"><%= recipe_food.food.name %></td>
          <td class="px-3 py-2"><%= recipe_food.quantity %></td>
          <td><%= @price %></td>
          <td>
              <div class="status w-64 flex justify-around text-xs">
                <span class="badge bg-blue-400 text-white rounded-sm px-1 py-0.5 uppercase grid place-items-center">
                  <%= link_to "Edit this recipe", edit_recipe_recipe_food_path(@recipe, recipe_food), class: "btn btn-primary" %>
                </span>
              </div>
          </td>

          <td>
              <div class="w-64 flex justify-around text-xs text-sm text-red-600 border-red-400 rounded-sm border-2 px-1 py-0.5">
              <%= button_to 'Delete', recipe_recipe_food_path(@recipe, id: recipe_food), method: :delete, data: { turbo: false }, class: 'btn btn-danger' %>
              </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  </div>
</div>

</div>

app/views/recipes/_recipe_foods.html.erb
<%= form_with model: @recipe_food, url: recipe_foods_path do |form| %>
    <% @recipes.each do |recipe| %>
        <%= form.hidden_field :recipe_id, value: recipe.id %>
        
        
    <% end %>
    <%= form.label :food_id, "Food" %>
    <%= form.select :food_id, Food.all.map { |food| [food.name, food.id] } %>
    <%= form.label :quantity, "Quantity" %>
    <%= form.number_field :quantity %>
    <%= form.submit "Add food" %>
<% end %>
<%= link_to "Back to recipes", recipes_path %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<div class="flex justify-center mt-48 mb-48 container mx-auto">
  <div class="w-4/5 bg-white shadow-lg p-10">
<h1 class="text-2xl font-bold border-b-2">Recipes</h1>

<div class="flex justify-end mt-4">
  <%= link_to "New recipe", new_recipe_path,  class: "py-3 px-6 bg-teal-500 mb-3 text-white hover:bg-orange-700" %>
  </div>
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>
</div>
</div>
</div>

app/views/recipes/new.html.erb
<h1 class='center'>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<%= link_to "Back to recipes", recipes_path, class: 'center' %>

app/views/recipes/show.html.erb
<%= render partial: 'recipe_details', locals: {recipe: @recipe} %>

<%# Popup section %>
<div class="popup hidden">
  <button class="close-btn btn bg-red-300">close </button>
  <h1>Generating Shopping List</h1>
  <p>Choose an inventory to use</p>

  <%= form_with url: shopping_list_index_path(recipe_id: @recipe.id, inventory_id: :inventory_id), method: :get do |form| %>    
    <%= form.hidden_field :recipe_id, value: @recipe.id %>
    <%= form.collection_select :inventory_id, @inventories.order(:name),:id,:name, :include_blank => "--Select inventory--" %>
    <%= form.submit "Generate Shopping List", class: 'btn bg-teal-300' %>
  <% end %>
</div>