config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'pages/home'
  root 'public_recipes#index'
  get 'general_shopping_list/index'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
   resources :recipes, only: [:index, :show, :new, :create] do
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :foods, only: [:index, :show, :new, :create, :destroy]
  resources :shopping_list, only: [:index, :create]
  resources :inventories do
    resources :inventory_foods, only: [:new, :create, :destroy, :index]
  end

end

app/views/shared/_navbar.html.erb
    <nav class="flex items-center justify-between flex-wrap bg-teal-500 p-6">
    <div class="flex items-center flex-shrink-0 text-white mr-6">
      <a href="#" class="font-semibold text-xl tracking-tight"><%=link_to "My Recipe", root_path%></a>
    </div>

    
    <div class="block lg:hidden">
      <button class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
        <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
      </button>
    </div>
    <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
      <div class="text-sm lg:flex-grow">
      <% if current_user %>
        <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
        <%= link_to "Foods", foods_path %>
        </a>
        <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
          <%= link_to "Recipes", recipes_path %>
        </a>
        </a>
        <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
          <%= link_to 'Inventories', inventories_path, class: "nav-link " %>
        </a>
      </div>
        </div>
    <div class="flex items-center flex-shrink-0 text-white">
      <%=button_to "Logout", destroy_user_session_path, method: :delete, class: "font-semibold text-xl tracking-tight" %>
    </div>
    <% end %>
    <% if !current_user %>
    <div class="flex justify-end text-white gap-3">
      <%=link_to "Login", new_user_session_path, class: "font-semibold text-xl tracking-tight" %>
      <%= link_to "Sign up", new_user_registration_path, class: "font-semibold text-xl tracking-tight text-end" %>
    </div>
    <% end %> 
  </nav>