config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'pages/home'
  root 'public_recipes#index'
  get 'general_shopping_list/index'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
   resources :recipes, only: [:index, :show, :new, :create] do
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :foods, only: [:index, :show, :new, :create, :destroy]
  resources :shopping_list, only: [:index, :create]
  resources :inventories do
    resources :inventory_foods, only: [:new, :create, :destroy, :index]
  end

end

app/models/food.rb
class Food < ApplicationRecord
  has_many :inventory_foods, dependent: :destroy
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods, dependent: :destroy

  validates :name, :measurement_unit, :price, presence: true
  validates :price, numericality: true, comparison: { greater_than: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  def index
    @foods = Food.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)

    puts
    puts @food.valid?
    puts @food.save
    if @food.save
      redirect_to foods_path, notice: 'Food was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @food = Food.find(params[:id])

    if @food.destroy
      redirect_to foods_path, notice: 'Food was successfully deleted.'
    else
      render :new, notice: 'Food was not deleted.'
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/views/foods/index.html.erb
<div class="flex items-center flex-col mt-32 container w-3/4 mx-auto">
  
  <%if @foods.any?%>
    <div id="foods" class="container flex flex-col gap-4" >
      <div class="food-btn self-center">
        <%= link_to "New Food", new_food_path, class: 'btn' %>
      </div>
      <table class="table table-striped">
        <thead>
          <tr>
            <th class="col-sm-4">Food</th>
            <th class="col-sm-4">Measurement Unit</th>
            <th class="col-sm-4">Price</th>
            <th class="col-sm-4">Actions</th>
          </tr>
        </thead> 
        <tbody>
          <% @foods.each do |food| %>
            <tr>
              <td class="col-sm-4"><%= food.name %></td>
              <td class="col-sm-4"><%= food.measurement_unit %></td>
              <td class="col-sm-4"><%= food.price %></td>
              <td class="col-sm-4"><%= button_to "Delete", food_path(food) , data: {turbo: false}, method: :delete, class: "btn bg-red-300" %></td>
            </tr>    
          <% end %>
        </tbody> 
      
      </table>
    </div>
  <%else%>
    <div id="foods" class="container flex flex-col gap-4" >
      <div class="food-btn self-center mb-5">
        <%= link_to "New Food", new_food_path, class: 'btn' %>
      </div>
    </div>
    <div class="w-3/5 bg-white shadow-lg p-10">
      <div>
        <p>No Foods yet</p>
      </div>
    <div>
  <%end%>
</div>

app/views/foods/new.html.erb
<div class="flex justify-center mt-48 mb-48 container mx-auto">
  <div class="w-3/5 bg-white shadow-lg pb-10 px-10 pt-5">
      <div class="flex justify-start my-4">
         <%= link_to 'Go back', foods_path, class: 'text-teal-500' %>
         </div>
      <h1 class="text-3xl font-bold border-b-2">Add New Food</h1>
     <div>
      <%= form_with model: @food, url: foods_path, local: true do |form| %>
        <p class="mb-3 mt-5"> 
      <%= form.label :name, class: 'font-semibold pb-1' %><br />
      <%= form.text_field :name, class: 'py-2 px-4 border w-full focus:outline-orange-400', placeholder: 'Food name'%>
        </p>
        <p class="mb-3"> 

      <%= form.label :measurement_unit, class: 'font-semibold pb-1'%><br/>
      <%= form.text_field :measurement_unit, class: 'py-2 px-4 border w-full focus:outline-orange-400', placeholder: 'grams / units'%>
      </p>
        <p class="mb-3">
      <%= form.label :price, class: 'font-semibold pb-1' %><br />
      <%= form.number_field :price, class: 'py-2 px-4 border w-full focus:outline-orange-400', placeholder: 'Price'%>
      </p>
      <p>
      <%= form.submit class: 'bg-orange-500 py-3 px-10 text-white hover:bg-orange-700 cursor-pointer' %>
    </p>
      <% end %>
      </div>
  </div>
</div>